import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("http://practice.automationtesting.in/")
shop_btn = driver.find_element_by_id("menu-item-40")
shop_btn.click()
driver.execute_script("window.scrollBy(0,300);")
book_wed_dev_add = driver.find_element_by_css_selector(".post-182 > a.button.product_type_simple.add_to_cart_button.ajax_add_to_cart")
book_wed_dev_add.click()
to_cart = driver.find_element_by_css_selector(".added_to_cart.wc-forward")
to_cart.click()
checkout_btn = WebDriverWait(driver, 20).until(
EC.element_to_be_clickable((By.CSS_SELECTOR, ".wc-proceed-to-checkout > a")))
checkout_btn.click()
first_name = WebDriverWait(driver, 20).until(
EC.element_to_be_clickable((By.ID, "billing_first_name")))
first_name.send_keys("Ilia")
last_name = driver.find_element_by_id("billing_last_name")
last_name.send_keys("Polyanichkin")
email = driver.find_element_by_id("billing_email")
email.send_keys("polenko_777@mail.ru")
phone = driver.find_element_by_id("billing_phone")
phone.send_keys("89998889999")
arrow = driver.find_element_by_css_selector("span.select2-arrow")
arrow.click()
enter_country = driver.find_element_by_id("s2id_autogen1_search")
enter_country.send_keys("Russia")
match = driver.find_element_by_css_selector("span.select2-match")
match.click()
address = driver.find_element_by_id("billing_address_1")
address.send_keys("Zaytzeva street")
apartment = driver.find_element_by_id("billing_address_2")
apartment.send_keys("house 21, flat 31")
town = driver.find_element_by_id("billing_city")
town.send_keys("St.Petersburg")
state = driver.find_element_by_id("billing_state")
state.send_keys("St.Petersburg")
postcode = driver.find_element_by_id("billing_postcode")
postcode.send_keys("198188")
driver.execute_script("window.scrollBy(0,600);")
time.sleep(5)
check = driver.find_element_by_id("payment_method_cheque")
check.click()
place_order = driver.find_element_by_id("place_order")
place_order.click()
order_received = WebDriverWait(driver, 10).until(
EC.text_to_be_present_in_element((By.CSS_SELECTOR, "p.woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
payment_method = WebDriverWait(driver, 10).until(
EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".method > strong"), "Check Payments"))